name: Mirror to Hssn19/quick-visit-checkin

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push `main` to mirror repo
        env:
          PAT: ${{ secrets.FIRST_GITHUB_PAT }}
        run: |
          git remote add mirror "https://x-access-token:${PAT}@github.com/Hssn19/quick-visit-checkin.git"
          git push mirror main:main --force
