name: Mirror to Hssn19/quick-visit-checkin

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add and push to mirror
        env:
          PAT: ${{ secrets.FIRST_GITHUB_PAT }}
        run: |
          REMOTE_URL="https://x-access-token:${PAT}@github.com/Hssn19/quick-visit-checkin.git"
          git remote add mirror "$REMOTE_URL"
          git push mirror --force
